receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  memory_limiter:
    limit_mib: 128

  resource:
    attributes:
      - key: service.name
        value: iot-edge-anomaly
        action: upsert
      - key: deployment.environment
        value: edge
        action: upsert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8888"
    const_labels:
      system: "iot-edge"

  logging:
    loglevel: info

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus, logging]

  extensions: []

  telemetry:
    logs:
      level: "info"
    metrics:
      address: 0.0.0.0:8888