apiVersion: v1
kind: Namespace
metadata:
  name: iot-edge-anomaly
  labels:
    name: iot-edge-anomaly
    app.kubernetes.io/name: iot-edge-anomaly
    app.kubernetes.io/version: "v4.0.0"
    app.kubernetes.io/component: edge-ai
    app.kubernetes.io/part-of: terragon-autonomous-sdlc
    app.kubernetes.io/managed-by: terragon
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: iot-edge-quota
  namespace: iot-edge-anomaly
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "4"
    pods: "20"
    services: "10"
    secrets: "10"
    configmaps: "10"