name: 🐛 Bug Report
description: Report a bug to help us improve the IoT Edge Anomaly Detection System
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us resolve the issue quickly.

  - type: checkboxes
    id: pre-checks
    attributes:
      label: Pre-submission Checklist
      description: Please verify you have completed these steps
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true
        - label: This issue is reproducible
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - LSTM Autoencoder Model
        - Data Preprocessing
        - Anomaly Detection Engine
        - Monitoring/Metrics
        - Container Deployment
        - Configuration
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (system unusable)
        - High (major functionality broken)
        - Medium (minor functionality affected)
        - Low (cosmetic or documentation)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Run command '...'
        2. With configuration '...'
        3. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Information about your environment
      value: |
        - OS: [e.g., Ubuntu 22.04, Raspberry Pi OS]
        - Architecture: [e.g., x86_64, ARM64]
        - Python Version: [e.g., 3.8.10]
        - Docker Version: [e.g., 24.0.0]
        - Container Runtime: [e.g., Docker Desktop, Podman]
        - Device Type: [e.g., Raspberry Pi 4, Intel NUC]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please include relevant logs, error messages, or screenshots
      placeholder: |
        ```
        Paste logs here...
        ```
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration Files
      description: Relevant configuration files (remove sensitive information)
      placeholder: |
        ```yaml
        # config/default.yaml
        ...
        ```
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Screenshots, related issues, workarounds, etc.
    validations:
      required: false